<html>
    <head>
        <meta charset="utf-8"/>
        <title>LO07-publi</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.18/angular-ui-router.min.js"></script>
        <script src="public/sha256.js"></script>
        <script src="public/auth.js"></script>
        <script src="public/app.js"></script>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body ng-app="LO07-publi">

      <ui-view></ui-view>

      <script type="text/ng-template" id="home">
        <h1>LO07-publi</h1>
        <div ng-if='errors && errors != ""'>
            Echec de la connexion : {{errors}}
        </div>
        <div>{{text}}</div>
        <button ng-click="register()">Inscription</button>
        <button ng-click="login()">Connexion</button>
        <button ng-click="logout()">Déconnexion</button>
      </script>

      <script type="text/ng-template" id="register">
        <h1>Inscription</h1>
        <div ng-if='errors && errors != ""'>
            Echec de la connexion : {{errors}}
        </div>
        <form>
          <label for="prenom">Prénom : </label>
          <input type="text" id="prenom" ng-model="user.prenom"> <br> <br>
          <label for="nom">Nom : </label>
          <input type="text" id="nom" ng-model="user.nom"> <br> <br>
          <label for="login">Identifiant : </label>
          <input type="text" id="login" ng-model="user.login"> <br> <br>
          <label for="password">Mot de passe : </label>
          <input type="password" id="password" ng-model="user.password"> <br> <br>
          <label for="organisation">Organisation : </label>
          <input type="text" id="organisation" ng-model="user.organisation"> <br> <br>
          <label for="equipe">Equipe : </label>
          <select id="equipe" ng-model="user.equipe" ng-options="equipe for equipe in equipes" ng-init="user.equipe = equipes[0]"></select> <br> <br>
          <button ng-click="register()">Inscription</button>
          <button ng-click="annuler()">Annuler</button>
        </form>
      </script>

      <script type="text/ng-template" id="login">
        <h1>Connexion</h1>
        <div ng-if='errors && errors != ""'>
            Echec de la connexion : {{errors}}
        </div>
        <form>
          <label for="login">Identifiant : </label>
          <input type="text" id="login" ng-model="login_info.username">
          <label for="password">Mot de passe :</label>
          <input type="password" id="password" ng-model="login_info.password">
          <button ng-click="login(login_info)">Connexion</button>
          <button ng-click="annuler()">Annuler</button>
        </form>
      </script>
    </body>
</html>
