<html>
    <head>
        <meta charset="utf-8"/>
        <title>LO07-publi</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.18/angular-ui-router.min.js"></script>
        <script src="public/libs/angular-base64-upload.js"></script>
        <script src="public/libs/sha256.js"></script>
        <script src="public/auth.js"></script>
        <script src="public/publi.js"></script>
        <script src="public/app.js"></script>
        <link rel="stylesheet" type="text/css" href="public/style.css">
    </head>
    <body ng-app="LO07-publi">
      <nav ng-controller="NavBar" class="nav">
        <ul>
          <li><button><a href="#">LO07-Publi</a></button></li>
          <li ng-show="loggedIn">{{currentUser()}}</li>
          <li ng-show="loggedIn"><button ng-click="logout()">Logout</button></li>
          <li ng-hide="loggedIn"><button ng-click="login()">Login</button></li>
          <li ng-hide="loggedIn"><button ng-click="register()">Register</button></li>
        </ul>
      </nav>

      <ui-view></ui-view>

      <script type="text/ng-template" id="home">
        <h1>LO07-publi</h1>
        <div ng-if='errors && errors != ""'>
            Echec de la connexion : {{errors}}
        </div>
        <button ng-click="publier()">Publier</button>
      </script>

      <script type="text/ng-template" id="register">
        <h1>Inscription</h1>
        <div ng-if='errors && errors != ""'>
            Echec de la connexion : {{errors}}
        </div>
        <form>
          <label for="prenom">Prénom : </label>
          <input type="text" id="prenom" ng-model="user.prenom"> <br> <br>
          <label for="nom">Nom : </label>
          <input type="text" id="nom" ng-model="user.nom"> <br> <br>
          <label for="login">Identifiant : </label>
          <input type="text" id="login" ng-model="user.username"> <br> <br>
          <label for="password">Mot de passe : </label>
          <input type="password" id="password" ng-model="user.password"> <br> <br>
          <label for="organisation">Organisation : </label>
          <input type="text" id="organisation" ng-model="user.organisation"> <br> <br>
          <label for="equipe">Equipe : </label>
          <select id="equipe" ng-model="user.equipe" ng-options="equipe for equipe in equipes" ng-init="user.equipe = equipes[0]"></select> <br> <br>
          <button ng-click="register()">Inscription</button>
          <button ng-click="annuler()">Annuler</button>
        </form>
      </script>

      <script type="text/ng-template" id="login">
        <h1>Connexion</h1>
        <div ng-if='errors && errors != ""'>
            Echec de la connexion : {{errors}}
        </div>
        <form>
          <label for="login">Identifiant : </label>
          <input type="text" id="login" ng-model="login_info.username">
          <label for="password">Mot de passe :</label>
          <input type="password" id="password" ng-model="login_info.password">
          <button ng-click="login(login_info)">Connexion</button>
          <button ng-click="annuler()">Annuler</button>
        </form>
      </script>

      <script type="text/ng-template" id="publish">
        <h1>Publier</h1>
        <div ng-if='errors && errors != ""'>
            Echec de la connexion : {{errors}}
        </div>
        <form>
          <label for="title">Titre : </label>
          <input type="text" id="title" ng-model="publi.title" required><br>
          <label for="description">Description : </label>
          <textarea id="description" ng-model="publi.description" required></textarea><br>
          <label for="status">Status : </label>
          <input type="text" id="status" ng-model="publi.status" required><br>
          <label for="journal">Journal : </label>
          <input type="text" id="journal" ng-model="publi.journal"><br>
          <label for="annee">Année : </label>
          <input type="text" id="annee" ng-model="publi.annee"><br>
          <label for="location">Lieu de la conférence : </label>
          <input type="text" id="location" ng-model="publi.location"><br>
          <label for="file">Fichier : </label>
          <input type='file' ng-model='publi.file' base-sixty-four-input required><br>
          <button ng-click="publish()">Publier</button>
        </form>
      </script>
    </body>
</html>
